'use client';
import { createContext, useContext, useState, useEffect } from 'react';

const t = {
  sr: {
    // Navbar
    listings: 'Oglasi',
    howItWorks: 'Kako funkcioniše',
    profile: 'Profil',
    login: 'Prijavi se',
    postAd: 'Postavi oglas',

    // Home / Search
    hero: 'Kupi i prodaj sve — brzo, sigurno, povoljno',
    heroSub: 'Hiljade oglasa u Srbiji. Provereni prodavci. Bez prevara.',
    searchPlaceholder: 'Šta tražiš?',
    search: 'Pretraži',
    allCats: 'Sve kategorije',
    electronics: 'Elektronika',
    cars: 'Automobili',
    realestate: 'Nekretnine',
    fashion: 'Moda',
    furniture: 'Nameštaj',
    gaming: 'Gaming',
    tools: 'Alati',
    books: 'Knjige',
    trust1: 'Provereni prodavci',
    trust2: 'Kupac zaštićen',
    trust3: 'Bez skrivenih troškova',
    trust4: 'Besplatno oglašavanje',
    categories: 'Kategorije',
    newListings: 'Novi oglasi',
    verified: 'Proveren',
    minPrice: 'Min Cena',
    maxPrice: 'Max Cena',
    sortBy: 'Sortiraj po',
    sortNewest: 'Najnovije',
    sortPriceAsc: 'Najjeftinije',
    sortPriceDesc: 'Najskuplje',
    advancedFilters: 'Napredni filteri',
    applyFilters: 'Primeni filtere',
    condition: 'Stanje',
    condNew: 'Novo',
    condUsed: 'Polovno',
    city: 'Grad',
    allCities: 'Svi gradovi',
    noResults: 'Nema rezultata',
    noResultsSub: 'Pokušajte da promenite filtere ili kriterijum pretrage.',
    showAll: 'Prikaži sve oglase',
    removeFilters: 'Ukloni sve filtere',
    loadMore: 'Učitaj još oglasa',
    loading: 'Učitavam...',
    resetAll: 'Resetuj sve',

    // Login
    loginTitle: 'Prijavi se',
    emailLabel: 'Email adresa',
    passwordLabel: 'Lozinka',
    loggingIn: 'Prijavljivanje...',
    noAccount: 'Nemaš nalog?',
    register: 'Registruj se',

    // Register
    registerTitle: 'Kreiraj nalog',
    usernameLabel: 'Korisničko ime',
    usernamePlaceholder: 'npr. marko123',
    passwordPlaceholder: 'Minimum 6 karaktera',
    creatingAccount: 'Kreiranje...',
    hasAccount: 'Već imaš nalog?',
    profileCreateError: 'Greška pri kreiranju profila: ',
    registerSuccess: 'Uspešno! Proveri email da potvrdiš nalog.',

    // Post Ad
    postAdTitle: 'Postavi oglas',
    adTitle: 'Naslov oglasa',
    description: 'Opis',
    descPlaceholder: 'Opiši šta prodaješ...',
    price: 'Cena (RSD)',
    cityLabel: 'Grad',
    category: 'Kategorija',
    chooseCat: 'Izaberi kategoriju',
    itemCondition: 'Stanje predmeta',
    photos: 'Fotografije (max 10)',
    photoTip: 'Preporučujemo kvalitetne fotografije iz više uglova.',
    addPhoto: 'Dodaj',
    posting: 'Postavljam...',
    postAdBtn: 'Postavi oglas',
    postSuccess: 'Oglas je uspešno postavljen!',
    mustBeLoggedIn: 'Morate biti prijavljeni da biste postavili oglas.',
    imageError: 'Greška pri obradi slika: ',
    maxImages: 'Maksimalno 10 slika je dozvoljeno.',

    // Profile
    logout: 'Odjavi se',
    myListings: 'Moji oglasi',
    saved: 'Sačuvano',
    messages: 'Poruke',
    settings: 'Podešavanja',
    activeListings: 'Aktivnih oglasa',
    verificationLevel: 'Nivo verifikacije',
    memberSince: 'Član od',
    noListings: 'Još nemaš aktivnih oglasa.',
    postFirst: 'Postavi prvi oglas',
    newListing: '+ Novi oglas',
    bump: '🚀 Obnovi',
    edit: 'Izmeni',
    delete: 'Obriši',
    view: 'Pogledaj',
    savedListings: 'Sačuvani oglasi',
    noFavorites: 'Nisi sačuvao/la nijedan oglas.',
    browseListings: 'Pregledaj oglase',
    inbox: 'Inbox poruka',
    inboxSub: 'Pregledaj sve primljene i poslate poruke na jednom mestu.',
    openInbox: 'Otvori inbox →',
    profileSettings: 'Podešavanja profila',
    username: 'Korisničko ime',
    fullName: 'Ime i Prezime',
    bio: 'Biografija (Bio)',
    bioPlaceholder: 'Reci nešto o sebi kupcima...',
    saving: 'Čuvanje...',
    saveChanges: 'Sačuvaj izmene',
    securityTitle: 'Sigurnost i Verifikacija',
    phone: 'Broj telefona',
    verified2: 'VERIFIKOVAN',
    password: 'Lozinka',
    lastChanged: 'Poslednji put promenjena: Nedavno',
    changePassword: 'Promeni lozinku →',
    logoutAll: 'Odjavi se sa svih uređaja',
    confirmDelete: 'Da li ste sigurni da želite da obrišete ovaj oglas?',
    deleteError: 'Greška pri brisanju: ',
    bumpWait: 'Ovaj oglas možete ponovo obnoviti za',
    bumpSuccess: 'Oglas je uspešno obnovljen i pomeren na vrh!',
    bumpError: 'Greška pri obnavljanju: ',
    updateProfileError: 'Greška pri ažuriranju: ',
    updateProfileSuccess: 'Profil je uspešno ažuriran!',
    avatarSuccess: 'Slika profila je uspešno promenjena!',
    avatarError: 'Greška pri uploadu slike: ',
    passwordResetSent: 'Link za resetovanje lozinke je poslat na vaš email.',
    userWord: 'Korisnik',

    // ContactForm
    contactMustLogin: 'Morate biti prijavljeni da biste poslali poruku.',
    contactEmpty: 'Poruka ne može biti prazna.',
    contactPlaceholder: 'Napiši poruku prodavcu...',
    contactSending: 'Slanje...',
    contactSend: 'Pošalji poruku',
    contactSent: '✓ Poruka je uspešno poslata prodavcu!',
    contactSeller: 'Kontaktiraj prodavca',

    // ReportButton
    reportBtn: '🚩 Prijavi oglas',
    reportTitle: 'Prijavi oglas',
    reportSub: 'Da li ste primetili nešto sumnjivo? Prijavite ovaj oglas našim moderatorima.',
    reportReasons: ['Prevara / Scam', 'Netačne informacije', 'Neprimeren sadržaj', 'Već prodato', 'Duplikat oglasa'],
    reportCancel: 'Odustani',
    reportSending: 'Slanje...',
    reportSubmit: 'Pošalji prijavu',
    reportSentTitle: 'Prijava poslata',
    reportSentSub: 'Hvala vam što nam pomažete da Povoljno24 ostane sigurno mesto.',
    reportMustLogin: 'Morate biti prijavljeni da biste prijavili oglas.',
    reportError: 'Greška: ',

    // ReviewList
    noReviews: 'Ovaj korisnik još uvek nema ocena.',

    // oglas/[id] page
    sellerLabel: 'Prodavac',
    sellerAllAds: 'Svi oglasi prodavca →',
    verifiedBadge: '✓ Proveren',
    verifiedSeller: '✓ Proveren prodavac',
    noDescription: 'Nema opisa.',
    descriptionLabel: 'Opis',
    phoneLabel: 'Telefon',
    breadcrumbHome: 'Početna',

    // poruke/page.js
    unknownListing: 'Nepoznat oglas',

    // prodavac/[id] page
    backToListings: '← Nazad na oglase',
    sellerAds: 'Oglasi prodavca',
    sellerReviews: 'Utisci kupaca',
    noSellerAds: 'Ovaj prodavac nema aktivnih oglasa.',
    reviewCount: 'ocena',
    verifiedPhone: '📱 Telefon verifikovan',
    verificationLevelLabel: 'Nivo verifikacije',
    activeAdsLabel: 'aktivnih oglasa',
    memberSinceLabel: 'Član od',

    // page.js search dropdown
    suggestionsCategories: 'Kategorije',
    suggestionsSearch: 'Pretraga',
    suggestionsSearchFor: 'Traži',

    // Messages (poruke list)
    messagesTitle: 'Poruke',
    messagesSub: 'Vaši razgovori sa kupcima i prodavcima',
    backToProfile: '← Profil',
    noConversations: 'Nema započetih razgovora',
    noConversationsSub: 'Pronađi oglas koji te zanima i pošalji poruku prodavcu.',
    browseAds: 'Pregledaj oglase',
    loadingConversations: 'Učitavanje razgovora...',
    notifications: 'Obaveštenja',
    noNotifications: 'Nema novih obaveštenja.',
    seeAllNotifications: 'Vidi sva obaveštenja',

    // Phone Verification
    phoneVerifyTitle: 'Verifikacija broja telefona',
    phoneVerifySub: 'Unesite vaš broj mobilnog telefona u internacionalnom formatu.',
    phoneVerifyFormatError: 'Broj mora početi sa + (npr. +3816...)',
    phoneVerifySendCode: 'Pošalji SMS kod',
    phoneVerifySendingCode: 'Slanje koda...',
    phoneVerifyEnterCode: 'Unesite 6-cifreni kod koji smo vam poslali na',
    phoneVerifySmsCode: 'SMS Kod',
    phoneVerifyConfirm: 'Potvrdi kod',
    phoneVerifyVerifying: 'Verifikacija...',
    phoneVerifySuccess: 'Uspešno verifikovano!',
    phoneVerifyConnected: 'Vaš broj {phone} je sada povezan sa profilom.',
    phoneVerifyCodeError: 'Netačan ili istekao kod.',
    back: 'Nazad',

    // Admin Dashboard
    adminPanel: 'POVOLJNO24 ADMIN PANEL',
    adminVerifying: 'Verifikacija administratorskih prava...',
    adminReports: 'Prijave',
    adminLoading: 'Učitavanje podataka...',
    adminListing: 'Oglas',
    adminReason: 'Razlog prijave',
    adminReporter: 'Prijavio',
    adminStatus: 'Status',
    adminActions: 'Akcije',
    adminDeleted: '[Obrisano]',
    adminDismiss: 'Odbaci prijavu',
    adminDeleteListing: 'Obriši oglas',
    adminViewListing: 'Pogledaj oglas',
    adminNoReports: 'Nema aktivnih prijava.',
    adminListingDeleted: 'Oglas obrisan.',
    adminReportDismissed: 'Prijava odbačena.',
    zoomImage: 'Povećaj sliku',
    zoomTip: 'Točkić za zumiranje • Klikni i prevuci za pomeranje',

    // Database Values (Mapping)
    db_elektronika: 'Elektronika',
    db_automobili: 'Automobili',
    db_nekretnine: 'Nekretnine',
    db_moda: 'Moda',
    db_namestaj: 'Nameštaj',
    db_gaming: 'Gaming',
    db_alati: 'Alati',
    db_knjige: 'Knjige',
    db_novo: 'Novo',
    db_polovno: 'Polovno',

    // Validation / Form
    valUsernameMin: 'Korisničko ime mora imati najmanje 3 karaktera.',
    valEmail: 'Unesite validnu email adresu.',
    valPasswordMin: 'Lozinka mora imati najmanje 6 karaktera.',
    valTitleMin: 'Naslov mora imati najmanje 3 karaktera.',
    valDescMin: 'Opis mora imati najmanje 10 karaktera.',
    valPricePos: 'Cena mora biti veća od 0.',
    valCity: 'Unesite validan grad.',
    valCat: 'Izaberite kategoriju.',
    valCond: 'Izaberite stanje predmeta.',
    placeholderExample: 'npr.',
    emailPlaceholder: 'tvoj@email.com',

    // Buttons / Labels
    save: 'Sačuvaj',
    savedAction: 'Sačuvano',
    removeSaved: 'Ukloni iz sačuvanih',
    saveAd: 'Sačuvaj oglas',

    // Chat page
    rateSeller: 'Oceni prodavca',
    yourRating: 'Vaša ocena',
    comment: 'Komentar (opciono)',
    commentPlaceholder: 'Kakvo je bilo iskustvo sa ovim prodavcem?',
    cancel: 'Otkaži',
    sendRating: 'Pošalji ocenu',
    sending2: 'Slanje...',
    messagePlaceholder: 'Napišite poruku...',
    ratingError: 'Greška pri oceni: ',
    sendError: 'Greška pri slanju poruke: ',
    listingLabel: 'Oglas: ',

    // Kako funkcionise
    hifTitle: 'Kupi i prodaj pametnije, brže i sigurnije',
    hifSub: 'Dobrodošli na Povoljno24.rs — platformu dizajniranu da spoji kupce i prodavce širom Srbije na najjednostavniji mogući način. Saznajte kako možete izvući maksimum iz našeg sajta.',
    startSelling: 'Započni prodaju',
    exploreAds: 'Istraži oglase',
    forWhom: 'Za koga je Povoljno24?',
    forWhomSub: 'Bilo da praznite tavan, pokrećete mali biznis, ili tražite odličnu ponudu — na pravom ste mestu.',
    forBuyers: 'Za Kupce',
    forBuyersSub: 'Pronađite sve što vam je potrebno po najpovoljnijim cenama. Od elektronike do nekretnina, naša platforma vam omogućava da pretražujete, filtrirate i direktno komunicirate sa proverenim prodavcima bez skrivenih provizija.',
    forBuyersList: ['Veliki izbor kategorija', 'Sigurna komunikacija', 'Bez posrednika i provizija'],
    forSellers: 'Za Prodavce',
    forSellersSub: 'Pretvorite stvari koje vam više ne trebaju u novac ili proširite svoj posao. Postavljanje oglasa je brzo, jednostavno i potpuno besplatno. Vaš oglas će videti hiljade potencijalnih kupaca.',
    forSellersList: ['Besplatno oglašavanje', 'Ogroman doseg publike', 'Intuitivno upravljanje oglasima'],
    stepsTitle: 'Kako funkcioniše u 3 koraka',
    step1Title: 'Kreiraj nalog',
    step1Sub: 'Registracija traje manje od minuta. Potrebna vam je samo email adresa kako biste počeli sa kupovinom ili prodajom.',
    step2Title: 'Postavi ili Pronađi',
    step2Sub: 'Dodajte fotografije, opis i cenu za vaš predmet, ili pretražite našu bazu oglasa koristeći napredne filtere.',
    step3Title: 'Dogovori se',
    step3Sub: 'Stupite u kontakt putem našeg bezbednog sistema za poruke. Dogovorite preuzimanje i završite transakciju.',
    whyTitle: 'Zašto izabrati Povoljno24?',
    whySecurity: 'Sigurnost na prvom mestu',
    whySecuritySub: 'Svi korisnici prolaze kroz proces verifikacije, a naš sistem za prijavu sumnjivih oglasa radi 24/7 kako bi vas zaštitio.',
    whySpeed: 'Brzina i efikasnost',
    whySpeedSub: 'Zahvaljujući modernom dizajnu i pametnoj pretrazi, pronalaženje onoga što vam treba nikada nije bilo brže.',
    whyMessages: 'Integrisane poruke',
    whyMessagesSub: 'Nema potrebe za razmenom brojeva telefona odmah. Komunicirajte bezbedno unutar platforme.',
    whyMobile: 'Prilagođeno svim uređajima',
    whyMobileSub: 'Kupujte i prodajte u pokretu. Naš sajt savršeno radi na mobilnim telefonima, tabletima i računarima.',
    ctaTitle: 'Spremni da počnete?',
    ctaSub: 'Pridružite se hiljadama zadovoljnih korisnika i postanite deo najveće rastuće zajednice za kupovinu i prodaju u Srbiji.',
    ctaBtn: 'Kreiraj besplatan nalog',

    // Footer
    aboutUs: 'O nama',
    help: 'Pomoć',
    terms: 'Uslovi korišćenja',
    contact: 'Kontakt',

    // Footer Pages Content
    aboutText1: 'Povoljno24 je vodeća platforma za kupovinu i prodaju u Srbiji, osnovana sa ciljem da poveže ljude na siguran i jednostavan način.',
    aboutText2: 'Naš tim svakodnevno radi na unapređenju korisničkog iskustva, implementirajući najsavremenije tehnologije i sisteme zaštite kako bi svaka transakcija bila uspešna.',
    ourMission: 'Naša misija',
    missionText: 'Stvoriti digitalno okruženje gde svako može da trguje sa poverenjem, doprinoseći lokalnoj ekonomiji i održivoj potrošnji.',
    
    faq1Title: 'Kako da postavim oglas?',
    faq1Text: 'Kliknite na dugme "Postavi oglas" u gornjem desnom uglu, popunite podatke o predmetu, dodajte slike i vaš oglas će biti vidljiv hiljadama korisnika.',
    faq2Title: 'Da li je korišćenje besplatno?',
    faq2Text: 'Da! Osnovno postavljanje oglasa na Povoljno24 je potpuno besplatno za sve korisnike.',
    faq3Title: 'Kako da kontaktiram prodavca?',
    faq3Text: 'Na stranici svakog oglasa možete videti dugme "Pošalji poruku" ili broj telefona ukoliko ga je prodavac ostavio.',
    needMoreHelp: 'Potrebna vam je dodatna pomoć?',
    contactSupportText: 'Naš tim podrške je tu za vas. Pišite nam na:',

    terms1Title: 'Opšte odredbe',
    terms1Text: 'Korišćenjem platforme Povoljno24 prihvatate uslove korišćenja i obavezujete se na poštovanje zakona Republike Srbije.',
    terms2Title: 'Odgovornost za sadržaj',
    terms2Text: 'Korisnici su isključivo odgovorni za tačnost podataka u svojim oglasima i kvalitet robe koju prodaju.',
    terms3Title: 'Zabranjeni sadržaji',
    terms3Text: 'Strogo je zabranjeno oglašavanje nelegalnih predmeta, opojnih sredstava, oružja i bilo kog oblika uvredljivog sadržaja.',
    terms4Title: 'Zaštita podataka',
    terms4Text: 'Vaši podaci su sigurni kod nas. Koristimo ih isključivo u svrhu omogućavanja funkcionisanja platforme.',

    contactSub: 'Imate pitanje ili sugestiju? Pošaljite nam poruku i odgovorićemo vam u najkraćem roku.',
    messageSent: 'Poruka je poslata!',
    messageSentSub: 'Hvala vam što ste nas kontaktirali. Naš tim će vas kontaktirati uskoro.',
    nameLabel: 'Vaše ime',
    messageLabel: 'Vaša poruka',
    sendMessage: 'Pošalji poruku',

    // Bottom Nav
    home: 'Početna',
    post: 'Postavi',

    // New keys
    errorPrefix: 'Greška: ',
    changeAvatar: 'PROMENI',
    phoneLabel: 'Broj telefona',
    fullNamePlaceholder: 'Marko Marković',
    usernamePlaceholder: 'npr. marko123',
    bumpBtn: '🚀 Obnovi',
    editBtn: 'Izmeni',
    deleteBtn: 'Obriši',
    userFallback: 'Korisnik',
    editAdTitle: 'Izmeni oglas',
    backToProfile: '← Nazad na profil',
    priceDropNotif: 'Cena je pala! Oglas koji pratite "{title}" je sada {price} RSD.',
    updateSuccess: 'Oglas je uspešno izmenjen!',
    loadingLabel: 'Učitavanje...',
    chooseCat: 'Izaberi kategoriju',
    backToAds: '← Nazad na oglase',
    langTooltip: 'Promeni jezik / Change language',
  },
  en: {
    // Navbar
    listings: 'Listings',
    howItWorks: 'How it works',
    profile: 'Profile',
    login: 'Sign in',
    postAd: 'Post an ad',

    // Home / Search
    hero: 'Buy and sell anything — fast, safe, affordable',
    heroSub: 'Thousands of listings in Serbia. Verified sellers. No scams.',
    searchPlaceholder: 'What are you looking for?',
    search: 'Search',
    allCats: 'All categories',
    electronics: 'Electronics',
    cars: 'Cars',
    realestate: 'Real estate',
    fashion: 'Fashion',
    furniture: 'Furniture',
    gaming: 'Gaming',
    tools: 'Tools',
    books: 'Books',
    trust1: 'Verified sellers',
    trust2: 'Buyer protected',
    trust3: 'No hidden fees',
    trust4: 'Free listings',
    categories: 'Categories',
    newListings: 'Latest listings',
    verified: 'Verified',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    sortBy: 'Sort by',
    sortNewest: 'Newest',
    sortPriceAsc: 'Cheapest',
    sortPriceDesc: 'Most expensive',
    advancedFilters: 'Advanced filters',
    applyFilters: 'Apply filters',
    condition: 'Condition',
    condNew: 'New',
    condUsed: 'Used',
    city: 'City',
    allCities: 'All cities',
    noResults: 'No results',
    noResultsSub: 'Try changing your filters or search term.',
    showAll: 'Show all listings',
    removeFilters: 'Remove all filters',
    loadMore: 'Load more listings',
    loading: 'Loading...',
    resetAll: 'Reset all',

    // Login
    loginTitle: 'Sign in',
    emailLabel: 'Email address',
    passwordLabel: 'Password',
    loggingIn: 'Signing in...',
    noAccount: "Don't have an account?",
    register: 'Register',

    // Register
    registerTitle: 'Create account',
    usernameLabel: 'Username',
    usernamePlaceholder: 'e.g. john123',
    passwordPlaceholder: 'Minimum 6 characters',
    creatingAccount: 'Creating...',
    hasAccount: 'Already have an account?',
    profileCreateError: 'Error creating profile: ',
    registerSuccess: 'Success! Check your email to confirm your account.',

    // Post Ad
    postAdTitle: 'Post an ad',
    adTitle: 'Ad title',
    description: 'Description',
    descPlaceholder: 'Describe what you are selling...',
    price: 'Price (RSD)',
    cityLabel: 'City',
    category: 'Category',
    chooseCat: 'Choose a category',
    itemCondition: 'Item condition',
    photos: 'Photos (max 10)',
    photoTip: 'We recommend high-quality photos from multiple angles.',
    addPhoto: 'Add',
    posting: 'Posting...',
    postAdBtn: 'Post ad',
    postSuccess: 'Your ad was posted successfully!',
    mustBeLoggedIn: 'You must be logged in to post an ad.',
    imageError: 'Image processing error: ',
    maxImages: 'Maximum 10 images allowed.',

    // Profile
    logout: 'Sign out',
    myListings: 'My listings',
    saved: 'Saved',
    messages: 'Messages',
    settings: 'Settings',
    activeListings: 'Active listings',
    verificationLevel: 'Verification level',
    memberSince: 'Member since',
    noListings: 'You have no active listings yet.',
    postFirst: 'Post your first ad',
    newListing: '+ New listing',
    bump: '🚀 Bump',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    savedListings: 'Saved listings',
    noFavorites: "You haven't saved any listings.",
    browseListings: 'Browse listings',
    inbox: 'Message inbox',
    inboxSub: 'View all received and sent messages in one place.',
    openInbox: 'Open inbox →',
    profileSettings: 'Profile settings',
    username: 'Username',
    fullName: 'Full name',
    bio: 'Bio',
    bioPlaceholder: 'Tell buyers something about yourself...',
    saving: 'Saving...',
    saveChanges: 'Save changes',
    securityTitle: 'Security & Verification',
    phone: 'Phone number',
    verified2: 'VERIFIED',
    password: 'Password',
    lastChanged: 'Last changed: Recently',
    changePassword: 'Change password →',
    logoutAll: 'Sign out of all devices',
    confirmDelete: 'Are you sure you want to delete this listing?',
    deleteError: 'Error deleting: ',
    bumpWait: 'You can bump this listing again in',
    bumpSuccess: 'Listing bumped to the top!',
    bumpError: 'Error bumping: ',
    updateProfileError: 'Error updating: ',
    updateProfileSuccess: 'Profile updated successfully!',
    avatarSuccess: 'Profile picture updated successfully!',
    avatarError: 'Error uploading image: ',
    passwordResetSent: 'A password reset link was sent to your email.',
    userWord: 'User',

    // ContactForm
    contactMustLogin: 'You must be logged in to send a message.',
    contactEmpty: 'Message cannot be empty.',
    contactPlaceholder: 'Write a message to the seller...',
    contactSending: 'Sending...',
    contactSend: 'Send message',
    contactSent: '✓ Message sent to seller successfully!',
    contactSeller: 'Contact seller',

    // ReportButton
    reportBtn: '🚩 Report listing',
    reportTitle: 'Report listing',
    reportSub: 'Did you notice something suspicious? Report this listing to our moderators.',
    reportReasons: ['Fraud / Scam', 'Inaccurate information', 'Inappropriate content', 'Already sold', 'Duplicate listing'],
    reportCancel: 'Cancel',
    reportSending: 'Sending...',
    reportSubmit: 'Submit report',
    reportSentTitle: 'Report submitted',
    reportSentSub: 'Thank you for helping keep Povoljno24 a safe place.',
    reportMustLogin: 'You must be logged in to report a listing.',
    reportError: 'Error: ',

    // ReviewList
    noReviews: 'This user has no ratings yet.',

    // oglas/[id] page
    sellerLabel: 'Seller',
    sellerAllAds: 'All seller listings →',
    verifiedBadge: '✓ Verified',
    verifiedSeller: '✓ Verified seller',
    noDescription: 'No description.',
    descriptionLabel: 'Description',
    phoneLabel: 'Phone',
    breadcrumbHome: 'Home',

    // poruke/page.js
    unknownListing: 'Unknown listing',

    // prodavac/[id] page
    backToListings: '← Back to listings',
    sellerAds: 'Seller listings',
    sellerReviews: 'Buyer reviews',
    noSellerAds: 'This seller has no active listings.',
    reviewCount: 'ratings',
    verifiedPhone: '📱 Phone verified',
    verificationLevelLabel: 'Verification level',
    activeAdsLabel: 'active listings',
    memberSinceLabel: 'Member since',

    // page.js search dropdown
    suggestionsCategories: 'Categories',
    suggestionsSearch: 'Search',
    suggestionsSearchFor: 'Search for',

    // Messages (poruke list)
    messagesTitle: 'Messages',
    messagesSub: 'Your conversations with buyers and sellers',
    backToProfile: '← Profile',
    noConversations: 'No conversations yet',
    noConversationsSub: 'Find a listing you are interested in and send the seller a message.',
    browseAds: 'Browse listings',
    loadingConversations: 'Loading conversations...',
    notifications: 'Notifications',
    noNotifications: 'No new notifications.',
    seeAllNotifications: 'See all notifications',

    // Phone Verification
    phoneVerifyTitle: 'Phone number verification',
    phoneVerifySub: 'Enter your mobile phone number in international format.',
    phoneVerifyFormatError: 'Number must start with + (e.g. +3816...)',
    phoneVerifySendCode: 'Send SMS code',
    phoneVerifySendingCode: 'Sending code...',
    phoneVerifyEnterCode: 'Enter the 6-digit code we sent to',
    phoneVerifySmsCode: 'SMS Code',
    phoneVerifyConfirm: 'Confirm code',
    phoneVerifyVerifying: 'Verifying...',
    phoneVerifySuccess: 'Successfully verified!',
    phoneVerifyConnected: 'Your number {phone} is now connected to your profile.',
    phoneVerifyCodeError: 'Incorrect or expired code.',
    back: 'Back',

    // Admin Dashboard
    adminPanel: 'POVOLJNO24 ADMIN PANEL',
    adminVerifying: 'Verifying administrator rights...',
    adminReports: 'Reports',
    adminLoading: 'Loading data...',
    adminListing: 'Listing',
    adminReason: 'Report reason',
    adminReporter: 'Reported by',
    adminStatus: 'Status',
    adminActions: 'Actions',
    adminDeleted: '[Deleted]',
    adminDismiss: 'Dismiss report',
    adminDeleteListing: 'Delete listing',
    adminViewListing: 'View listing',
    adminNoReports: 'No active reports.',
    adminListingDeleted: 'Listing deleted.',
    adminReportDismissed: 'Report dismissed.',
    zoomImage: 'Enlarge image',
    zoomTip: 'Scroll to zoom • Click and drag to move',

    // Database Values (Mapping)
    db_elektronika: 'Electronics',
    db_automobili: 'Cars',
    db_nekretnine: 'Real Estate',
    db_moda: 'Fashion',
    db_namestaj: 'Furniture',
    db_gaming: 'Gaming',
    db_alati: 'Tools',
    db_knjige: 'Books',
    db_novo: 'New',
    db_polovno: 'Used',

    // Validation / Form
    valUsernameMin: 'Username must be at least 3 characters.',
    valEmail: 'Please enter a valid email address.',
    valPasswordMin: 'Password must be at least 6 characters.',
    valTitleMin: 'Title must be at least 3 characters.',
    valDescMin: 'Description must be at least 10 characters.',
    valPricePos: 'Price must be greater than 0.',
    valCity: 'Enter a valid city.',
    valCat: 'Select a category.',
    valCond: 'Select item condition.',
    placeholderExample: 'e.g.',
    emailPlaceholder: 'your@email.com',

    // Buttons / Labels
    save: 'Save',
    savedAction: 'Saved',
    removeSaved: 'Remove from saved',
    saveAd: 'Save ad',

    // Chat page
    rateSeller: 'Rate seller',
    yourRating: 'Your rating',
    comment: 'Comment (optional)',
    commentPlaceholder: 'How was your experience with this seller?',
    cancel: 'Cancel',
    sendRating: 'Submit rating',
    sending2: 'Sending...',
    messagePlaceholder: 'Write a message...',
    ratingError: 'Rating error: ',
    sendError: 'Error sending message: ',
    listingLabel: 'Listing: ',

    // Kako funkcionise
    hifTitle: 'Buy and sell smarter, faster and safer',
    hifSub: 'Welcome to Povoljno24.rs — a platform designed to connect buyers and sellers across Serbia in the simplest way possible. Find out how to get the most out of our site.',
    startSelling: 'Start selling',
    exploreAds: 'Explore listings',
    forWhom: 'Who is Povoljno24 for?',
    forWhomSub: 'Whether you are clearing out the attic, starting a small business, or looking for a great deal — you are in the right place.',
    forBuyers: 'For Buyers',
    forBuyersSub: 'Find everything you need at the best prices. From electronics to real estate, our platform lets you search, filter and communicate directly with verified sellers with no hidden fees.',
    forBuyersList: ['Wide range of categories', 'Secure communication', 'No middlemen or commissions'],
    forSellers: 'For Sellers',
    forSellersSub: 'Turn things you no longer need into cash or grow your business. Posting an ad is fast, easy and completely free. Your listing will be seen by thousands of potential buyers.',
    forSellersList: ['Free listings', 'Massive audience reach', 'Intuitive ad management'],
    stepsTitle: 'How it works in 3 steps',
    step1Title: 'Create an account',
    step1Sub: 'Registration takes less than a minute. All you need is an email address to start buying or selling.',
    step2Title: 'Post or Find',
    step2Sub: 'Add photos, a description and a price for your item, or search our listing database using advanced filters.',
    step3Title: 'Make a deal',
    step3Sub: 'Get in touch via our secure messaging system. Arrange a pickup and complete the transaction.',
    whyTitle: 'Why choose Povoljno24?',
    whySecurity: 'Security first',
    whySecuritySub: 'All users go through a verification process, and our suspicious listing reporting system runs 24/7 to protect you.',
    whySpeed: 'Speed and efficiency',
    whySpeedSub: 'Thanks to modern design and smart search, finding what you need has never been faster.',
    whyMessages: 'Integrated messaging',
    whyMessagesSub: 'No need to exchange phone numbers right away. Communicate safely within the platform.',
    whyMobile: 'Works on all devices',
    whyMobileSub: 'Buy and sell on the go. Our site works perfectly on mobile phones, tablets and computers.',
    ctaTitle: 'Ready to get started?',
    ctaSub: 'Join thousands of satisfied users and become part of the largest growing buy-and-sell community in Serbia.',
    ctaBtn: 'Create a free account',

    // Footer
    aboutUs: 'About us',
    help: 'Help',
    terms: 'Terms of use',
    contact: 'Contact',

    // Footer Pages Content
    aboutText1: 'Povoljno24 is the leading buy-and-sell platform in Serbia, founded with the goal of connecting people in a secure and simple way.',
    aboutText2: 'Our team works daily to improve the user experience, implementing state-of-the-art technologies and protection systems to ensure every transaction is successful.',
    ourMission: 'Our Mission',
    missionText: 'To create a digital environment where everyone can trade with confidence, contributing to the local economy and sustainable consumption.',
    
    faq1Title: 'How do I post an ad?',
    faq1Text: 'Click the "Post an ad" button in the top right corner, fill in the item details, add photos, and your ad will be visible to thousands of users.',
    faq2Title: 'Is it free to use?',
    faq2Text: 'Yes! Basic ad posting on Povoljno24 is completely free for all users.',
    faq3Title: 'How do I contact a seller?',
    faq3Text: 'On every listing page, you can see a "Send message" button or a phone number if the seller has provided one.',
    needMoreHelp: 'Need more help?',
    contactSupportText: 'Our support team is here for you. Email us at:',

    terms1Title: 'General Terms',
    terms1Text: 'By using the Povoljno24 platform, you accept the terms of use and commit to complying with the laws of the Republic of Serbia.',
    terms2Title: 'Content Responsibility',
    terms2Text: 'Users are solely responsible for the accuracy of data in their ads and the quality of the goods they sell.',
    terms3Title: 'Prohibited Content',
    terms3Text: 'Advertising illegal items, narcotics, weapons, and any form of offensive content is strictly prohibited.',
    terms4Title: 'Data Protection',
    terms4Text: 'Your data is safe with us. We use it exclusively for the purpose of enabling the platforms operation.',

    contactSub: 'Have a question or suggestion? Send us a message and we will get back to you as soon as possible.',
    messageSent: 'Message sent!',
    messageSentSub: 'Thank you for contacting us. Our team will get back to you shortly.',
    nameLabel: 'Your Name',
    messageLabel: 'Your Message',
    sendMessage: 'Send Message',

    // Bottom Nav
    home: 'Home',
    post: 'Post',

    // New keys
    errorPrefix: 'Error: ',
    changeAvatar: 'CHANGE',
    phoneLabel: 'Phone number',
    fullNamePlaceholder: 'John Doe',
    usernamePlaceholder: 'e.g. john123',
    bumpBtn: '🚀 Bump',
    editBtn: 'Edit',
    deleteBtn: 'Delete',
    userFallback: 'User',
    editAdTitle: 'Edit ad',
    backToProfile: '← Back to profile',
    priceDropNotif: 'Price dropped! The ad you follow "{title}" is now {price} RSD.',
    updateSuccess: 'Ad updated successfully!',
    loadingLabel: 'Loading...',
    chooseCat: 'Choose category',
    backToAds: '← Back to ads',
    langTooltip: 'Change language / Promeni jezik',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState('sr');

  useEffect(() => {
    const saved = localStorage.getItem('povoljno24_lang');
    if (saved === 'sr' || saved === 'en') setLangState(saved);
  }, []);

  const setLang = (newLang) => {
    setLangState(newLang);
    localStorage.setItem('povoljno24_lang', newLang);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: t[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
